-- FPTU WORK v7 - Project-centric upgrade
-- Run once in Supabase SQL Editor AFTER the earlier base schema / permission patches.

create extension if not exists "pgcrypto";

-- 1) Workspace-level custom permissions
alter table public.memberships add column if not exists can_create_project boolean not null default false;
alter table public.memberships add column if not exists can_review_task boolean not null default false;
alter table public.memberships add column if not exists can_assign_outside_project boolean not null default false;
alter table public.memberships add column if not exists can_view_team_report boolean not null default false;
alter table public.memberships add column if not exists can_archive_project boolean not null default false;

-- 2) Project becomes the central unit
alter table public.projects add column if not exists code text;
alter table public.projects add column if not exists lead_id uuid;
alter table public.projects add column if not exists owner_id uuid;
alter table public.projects add column if not exists start_at timestamptz;
alter table public.projects add column if not exists due_at timestamptz;
alter table public.projects add column if not exists priority text not null default 'medium';
alter table public.projects add column if not exists visibility text not null default 'team';
alter table public.projects add column if not exists require_task_review boolean not null default true;
alter table public.projects add column if not exists health text not null default 'on_track';
alter table public.projects add column if not exists archived_at timestamptz;
alter table public.projects add column if not exists cancelled_at timestamptz;
alter table public.projects add column if not exists cancel_reason text;

-- Add FKs only if they do not exist.
do $$ begin
  alter table public.projects add constraint projects_lead_id_fkey foreign key (lead_id) references public.profiles(id) on delete set null;
exception when duplicate_object then null; end $$;
do $$ begin
  alter table public.projects add constraint projects_owner_id_fkey foreign key (owner_id) references public.profiles(id) on delete set null;
exception when duplicate_object then null; end $$;

create unique index if not exists projects_workspace_code_uq on public.projects(workspace_id, code) where code is not null;
create index if not exists idx_projects_team on public.projects(team_id);
create index if not exists idx_projects_lead on public.projects(lead_id);

-- 3) Project membership + permission overrides
create table if not exists public.project_members (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role_in_project text not null default 'member' check (role_in_project in ('owner','lead','member','guest')),
  can_create_task boolean not null default true,
  can_assign_task boolean not null default true,
  can_review_task boolean not null default false,
  can_manage_members boolean not null default false,
  can_assign_outside_project boolean not null default false,
  joined_at timestamptz not null default now(),
  unique(project_id,user_id)
);

create index if not exists idx_project_members_user on public.project_members(user_id);

-- 4) Project discussions / files / activity
create table if not exists public.project_comments (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  content text not null,
  parent_comment_id uuid references public.project_comments(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  deleted_at timestamptz
);

create table if not exists public.project_files (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  file_name text,
  file_url text not null,
  file_type text,
  uploaded_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.project_activity_logs (
  id bigint generated by default as identity primary key,
  project_id uuid not null references public.projects(id) on delete cascade,
  actor_id uuid references public.profiles(id) on delete set null,
  action text not null,
  old_value jsonb,
  new_value jsonb,
  created_at timestamptz not null default now()
);

-- 5) Task grouping / workflow enhancements
alter table public.tasks alter column project_id drop not null;
alter table public.tasks add column if not exists review_result text;
alter table public.tasks add column if not exists review_note text;
alter table public.tasks add column if not exists accepted_by uuid references public.profiles(id) on delete set null;
alter table public.tasks add column if not exists parent_task_id uuid references public.tasks(id) on delete cascade;
alter table public.tasks add column if not exists is_personal boolean not null default false;

-- 6) Invitation can optionally join a specific Project
alter table public.invitations add column if not exists project_id uuid references public.projects(id) on delete cascade;

-- 7) Helper permission functions (SECURITY DEFINER avoids RLS recursion)
create or replace function public.my_workspace_membership(p_workspace_id uuid)
returns public.memberships
language sql stable security definer set search_path=public
as $$
  select m from public.memberships m
  where m.workspace_id=p_workspace_id and m.user_id=auth.uid() and m.status='active'
  limit 1;
$$;

create or replace function public.can_access_project(p_project_id uuid)
returns boolean
language sql stable security definer set search_path=public
as $$
  select exists(
    select 1 from public.projects p
    left join public.memberships m on m.workspace_id=p.workspace_id and m.user_id=auth.uid() and m.status='active'
    left join public.project_members pm on pm.project_id=p.id and pm.user_id=auth.uid()
    where p.id=p_project_id and (
      m.role='manager'
      or p.lead_id=auth.uid()
      or p.owner_id=auth.uid()
      or pm.user_id=auth.uid()
      or (p.visibility='workspace' and m.user_id is not null)
      or (p.visibility='team' and m.team_id=p.team_id)
    )
  );
$$;

create or replace function public.can_create_project_in_team(p_workspace_id uuid,p_team_id uuid)
returns boolean
language sql stable security definer set search_path=public
as $$
  select exists(
    select 1 from public.memberships m
    where m.workspace_id=p_workspace_id and m.user_id=auth.uid() and m.status='active'
      and (m.role='manager' or (m.role='team_lead' and m.team_id=p_team_id) or m.can_create_project)
  );
$$;

create or replace function public.can_manage_project(p_project_id uuid)
returns boolean
language sql stable security definer set search_path=public
as $$
  select exists(
    select 1 from public.projects p
    left join public.memberships m on m.workspace_id=p.workspace_id and m.user_id=auth.uid() and m.status='active'
    left join public.project_members pm on pm.project_id=p.id and pm.user_id=auth.uid()
    where p.id=p_project_id and (
      m.role='manager' or p.lead_id=auth.uid() or p.owner_id=auth.uid() or pm.role_in_project in ('owner','lead') or pm.can_manage_members
    )
  );
$$;

create or replace function public.can_create_task_in_project(p_project_id uuid)
returns boolean
language sql stable security definer set search_path=public
as $$
  select exists(
    select 1 from public.projects p
    left join public.memberships m on m.workspace_id=p.workspace_id and m.user_id=auth.uid() and m.status='active'
    left join public.project_members pm on pm.project_id=p.id and pm.user_id=auth.uid()
    where p.id=p_project_id and (
      m.role='manager' or (m.role='team_lead' and m.team_id=p.team_id) or pm.can_create_task
    )
  );
$$;

-- Replace the old task-access helper so Project members can collaborate.
create or replace function public.can_access_task(p_task_id uuid)
returns boolean
language sql stable security definer set search_path=public
as $$
  select exists (
    select 1 from public.tasks t
    left join public.memberships m on m.workspace_id=t.workspace_id and m.user_id=auth.uid() and m.status='active'
    left join public.task_watchers w on w.task_id=t.id and w.user_id=auth.uid()
    left join public.project_members pm on pm.project_id=t.project_id and pm.user_id=auth.uid()
    where t.id=p_task_id and (
      m.role='manager' or t.assigner_id=auth.uid() or t.assignee_id=auth.uid() or w.user_id=auth.uid()
      or (m.role='team_lead' and m.team_id=t.team_id) or pm.user_id=auth.uid()
    )
  );
$$;

-- 8) RLS
alter table public.project_members enable row level security;
alter table public.project_comments enable row level security;
alter table public.project_files enable row level security;
alter table public.project_activity_logs enable row level security;

-- Projects: project-centric visibility
drop policy if exists "project_read_member" on public.projects;
drop policy if exists "projects_read_access" on public.projects;
create policy "projects_read_access" on public.projects for select to authenticated
using (public.can_access_project(id));

drop policy if exists "projects_insert_allowed" on public.projects;
create policy "projects_insert_allowed" on public.projects for insert to authenticated
with check (created_by=auth.uid() and public.can_create_project_in_team(workspace_id,team_id));

drop policy if exists "projects_update_manage" on public.projects;
create policy "projects_update_manage" on public.projects for update to authenticated
using (public.can_manage_project(id)) with check (public.can_manage_project(id));

-- Project members
drop policy if exists "project_members_read" on public.project_members;
create policy "project_members_read" on public.project_members for select to authenticated
using (public.can_access_project(project_id));

drop policy if exists "project_members_manage" on public.project_members;
create policy "project_members_manage" on public.project_members for all to authenticated
using (public.can_manage_project(project_id)) with check (public.can_manage_project(project_id));

-- Members are contributors: they can create tasks in projects they belong to.
drop policy if exists "task_insert_member" on public.tasks;
drop policy if exists "tasks_insert_project_member" on public.tasks;
create policy "tasks_insert_project_member" on public.tasks for insert to authenticated
with check (
  assigner_id=auth.uid()
  and public.is_workspace_member(workspace_id)
  and (project_id is null or public.can_create_task_in_project(project_id))
);

-- Task updates are allowed to collaborators; workflow enforcement can be tightened later with a trigger.
drop policy if exists "task_update_access" on public.tasks;
create policy "task_update_access" on public.tasks for update to authenticated
using (public.can_access_task(id)) with check (public.can_access_task(id));

-- Project discussion / files / activity
drop policy if exists "project_comments_read" on public.project_comments;
create policy "project_comments_read" on public.project_comments for select to authenticated using (public.can_access_project(project_id));
drop policy if exists "project_comments_insert" on public.project_comments;
create policy "project_comments_insert" on public.project_comments for insert to authenticated with check (user_id=auth.uid() and public.can_access_project(project_id));
drop policy if exists "project_comments_update_self" on public.project_comments;
create policy "project_comments_update_self" on public.project_comments for update to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());

drop policy if exists "project_files_read" on public.project_files;
create policy "project_files_read" on public.project_files for select to authenticated using (public.can_access_project(project_id));
drop policy if exists "project_files_insert" on public.project_files;
create policy "project_files_insert" on public.project_files for insert to authenticated with check (uploaded_by=auth.uid() and public.can_access_project(project_id));

drop policy if exists "project_activity_read" on public.project_activity_logs;
create policy "project_activity_read" on public.project_activity_logs for select to authenticated using (public.can_access_project(project_id));

-- 9) Project activity trigger
create or replace function public.log_project_changes()
returns trigger language plpgsql security definer set search_path=public
as $$
declare v_actor uuid:=auth.uid();
begin
 if tg_op='INSERT' then
   insert into public.project_activity_logs(project_id,actor_id,action,new_value) values(new.id,coalesce(v_actor,new.created_by),'project_created',to_jsonb(new));
   return new;
 end if;
 if old.description is distinct from new.description then insert into public.project_activity_logs(project_id,actor_id,action,old_value,new_value) values(new.id,v_actor,'project_description_changed',jsonb_build_object('description',old.description),jsonb_build_object('description',new.description)); end if;
 if old.due_at is distinct from new.due_at then insert into public.project_activity_logs(project_id,actor_id,action,old_value,new_value) values(new.id,v_actor,'project_deadline_changed',jsonb_build_object('due_at',old.due_at),jsonb_build_object('due_at',new.due_at)); end if;
 if old.status is distinct from new.status then insert into public.project_activity_logs(project_id,actor_id,action,old_value,new_value) values(new.id,v_actor,'project_status_changed',jsonb_build_object('status',old.status),jsonb_build_object('status',new.status)); end if;
 return new;
end $$;
drop trigger if exists trg_project_activity on public.projects;
create trigger trg_project_activity after insert or update on public.projects for each row execute function public.log_project_changes();

-- 10) Invite flow now optionally auto-adds Project membership.
create or replace function public.accept_invitation(p_token text)
returns jsonb
language plpgsql security definer set search_path=public
as $$
declare
  inv public.invitations;
  uid uuid:=auth.uid();
begin
  if uid is null then raise exception 'Not authenticated'; end if;
  select * into inv from public.invitations where token=p_token for update;
  if inv.id is null then raise exception 'Invite not found'; end if;
  if inv.revoked_at is not null then raise exception 'Invite revoked'; end if;
  if inv.expires_at is not null and inv.expires_at<now() then raise exception 'Invite expired'; end if;
  if inv.max_uses is not null and inv.usage_count>=inv.max_uses then raise exception 'Invite limit reached'; end if;

  insert into public.memberships(workspace_id,team_id,user_id,role,status)
  values(inv.workspace_id,inv.team_id,uid,inv.role,'active')
  on conflict(workspace_id,user_id) do update set status='active', team_id=coalesce(excluded.team_id,public.memberships.team_id);

  if inv.project_id is not null then
    insert into public.project_members(project_id,user_id,role_in_project,can_create_task,can_assign_task)
    values(inv.project_id,uid,'member',true,true)
    on conflict(project_id,user_id) do nothing;
  end if;

  insert into public.invitation_uses(invitation_id,user_id) values(inv.id,uid) on conflict do nothing;
  update public.invitations set usage_count=(select count(*) from public.invitation_uses where invitation_id=inv.id) where id=inv.id;
  return jsonb_build_object('workspace_id',inv.workspace_id,'team_id',inv.team_id,'project_id',inv.project_id,'role',inv.role);
end $$;

-- 11) Realtime
DO $$ BEGIN alter publication supabase_realtime add table public.projects; EXCEPTION when duplicate_object then null; END $$;
DO $$ BEGIN alter publication supabase_realtime add table public.project_members; EXCEPTION when duplicate_object then null; END $$;
DO $$ BEGIN alter publication supabase_realtime add table public.project_comments; EXCEPTION when duplicate_object then null; END $$;
DO $$ BEGIN alter publication supabase_realtime add table public.project_activity_logs; EXCEPTION when duplicate_object then null; END $$;

-- 12) Backfill project lead/owner for existing projects where possible.
update public.projects p
set lead_id=coalesce(p.lead_id,p.created_by), owner_id=coalesce(p.owner_id,p.created_by), code=coalesce(p.code,upper(left(regexp_replace(p.name,'[^A-Za-z0-9]+','','g'),12)))
where p.lead_id is null or p.owner_id is null or p.code is null;

-- Add current project creators to project_members.
insert into public.project_members(project_id,user_id,role_in_project,can_create_task,can_assign_task,can_review_task,can_manage_members)
select p.id,coalesce(p.lead_id,p.created_by),'lead',true,true,true,true
from public.projects p where coalesce(p.lead_id,p.created_by) is not null
on conflict(project_id,user_id) do nothing;

select 'FPTU Work v7 Project-centric upgrade completed' as result;
